{{- if not .Values.secretProviderClass.enabled }}
{{- include "epi.secret" (list $ . "" (dict)) }}
---
{{- include "leafletReader.secret" (list $ . "" (dict)) }}
{{- else }}
{{- include "epi.secretProviderClass" (list $ . "" (dict)) }}
---
{{- include "leafletReader.secretProviderClass" (list $ . "" (dict)) }}
{{- end }}
